### ISSUE TITLE
Four issues (balance and bugs)

### ISSUE THREAD

**Issue by GizmoFestus** [arcadia-redux/overthrow2#185] opened 2021-12-21 21:26 UTC
1. Silencer shouldn't have "Last Word mutes enemies" since this talent is replaced by +1 int in lvl 25 
2. People leaving in almost tie situations force the highest score teams to win. For example when the "kills to win" is 130 in octet and three teams have 129, 128 and 128 kills the highest score team wins after any full leave.
3. Gem respawn time should be lowered from 10 to 5-6 minutes (at least in octet). It's usually not bought early, you buy it in midgame and 
4. Fix the fact that Helm of the Dominator works on wards. If observer/sentry ward gets the aura from team, it will require 3 hits to kill, not 2. And other wards like tombstone, mana ward and shadow shaman's snakes become more hard to kill

**Comment by Draze22** [comment] 2022-03-29 04:25
1. Fixed next patch.
2. Duplicate of issue #197.
3. Gem stock time reduced to 5 minutes next patch.
4. Duplicate of #203.

**Closed by Draze22** 2022-03-29 04:25 UTC
